// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:
// Answer:  76576500


 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

#include <iostream>
using namespace std;
	
int main(){
	
for (int i = 1; 1 ; i++){
	int sum = 0;
	int count = 0;
	sum = (i*(i+1))/2;
	for (int k=1 ; k * k<= sum; k++){
		if( sum%k == 0)count++;
		
	}
	if(count >250){
		cout<<endl<<endl<<endl<<"triangle number : "<< sum<< " no of devisiors : " << count<<endl;
		break;
		}
}
	return 0;	
}
